In [ ]:
import pandas as pd

In [28]:
df_phrase = pd.read_csv(rf"C:\Users\davih\OneDrive\Documentos\PROJETOS\Fiap\ANO 2\Cardio IA\config\Frases_simuladas.txt", header=None, names=['frases'])
df_phrase['risco'] = None
display(df_phrase)

                                              frases risco
0  Cerca de uma semana sinto um formigamento cons...  None
1  Ha tres dias sinto um zumbido persistente no o...  None
2  Sinto um aperto na garganta e uma leve falta d...  None
3  Apresento uma tosse seca e persistente ha duas...  None
4  Estou com uma sensibilidade extrema nos dentes...  None
5  Ha dois dias sinto dor nas costas ao ficar mui...  None
6  Desde a semana passada sinto um cansaco excess...  None
7  Desde ontem sinto uma pressao na regiao dos ol...  None
8  Estou com dor no pescoco por tres dias, especi...  None
9  Desde a semana passada tenho notado perda de a...  None

In [ ]:
import pandas as pd
import unicodedata

# 1. Função para normalizar o texto (remover acentos, aspas e padronizar minúsculas)
def normalizar_texto(texto):
    if isinstance(texto, str):
        # Remove acentos e converte para ASCII
        texto_sem_acento = unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('ASCII')
        return texto_sem_acento.lower().strip('"')
    return texto

# Carregar os dados

# Definição das regras de classificaçao 
regras_risco = {
    'Alto Risco': ['falta de ar', 'tosse seca', 'cansaco excessivo'], 
    'Medio Risco': ['perda de apetite'], 
    'Baixo Risco': ['formigamento', 'zumbido', 'dor', 'sensibilidade']
}

# Função que percorre o dicionário e classifica a frase
def aplicar_classificacao(frase):
    texto = normalizar_texto(frase)
  
    for nivel, palavras in regras_risco.items():
        if any(palavra in texto for palavra in palavras):
            return nivel
            
    return "Nao Identificado"

#  Criar a coluna de risco e aplicar a função
df_phrase['risco'] = df_phrase['frases'].apply(aplicar_classificacao)

#  Exibir o resultado final
display(df_phrase)

# Salvar o resultado para a entrega da Fiap
# df_phrase.to_csv("Frases_classificadas.csv", index=False)

                                              frases        risco
0  Cerca de uma semana sinto um formigamento cons...  Baixo Risco
1  Ha tres dias sinto um zumbido persistente no o...  Baixo Risco
2  Sinto um aperto na garganta e uma leve falta d...   Alto Risco
3  Apresento uma tosse seca e persistente ha duas...   Alto Risco
4  Estou com uma sensibilidade extrema nos dentes...  Baixo Risco
5  Ha dois dias sinto dor nas costas ao ficar mui...  Baixo Risco
6  Desde a semana passada sinto um cansaco excess...   Alto Risco
7  Desde ontem sinto uma pressao na regiao dos ol...  Baixo Risco
8  Estou com dor no pescoco por tres dias, especi...  Baixo Risco
9  Desde a semana passada tenho notado perda de a...  Medio Risco